version: '3.7'

services:
  node:
    build: './node'
    # image: node:13.8
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ..:/home/node/app
    command: 'npm run start:webpack' # comment this line if you want to serve but not build
    restart: always # comment this line if you want to serve but not build
    # command: 'npm --version' # UNcomment this line if you want to serve but not build
