version: '3.9'

services:
  dev:
    build: ./doenet_docker/snowpack
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/home/node/workspace
      - node_modules:/home/node/workspace/node_modules
      - /home/node/workspace/dist_local
    networks:
      - dev_net
    command: tail -f /dev/null

  apache:
    build: './doenet_docker/apache'
    volumes:
      - ./src/api:/usr/local/apache2/htdocs/api
      - ./dist/media:/usr/local/apache2/htdocs/media
    networks:
      - dev_net
    depends_on:
      - php
      - mysql
    restart: always

  php:
    build: './doenet_docker/php'
    volumes:
      - ./src/api:/usr/local/apache2/htdocs/api
      - vendor:/usr/local/apache2/htdocs/api/vendor
    networks:
      - dev_net
    restart: always

  mysql:
    build: './doenet_docker/mysql'
    ports:
      - 3306:3306
    volumes:
      - ./doenet_docker/volumes/db:/var/lib/mysql
      - ./doenet_docker/volumes/db_init:/docker-entrypoint-initdb.d
    networks:
      - dev_net
    restart: always

volumes:
  node_modules:
  vendor:

networks:
  dev_net:
