version: '3'
services:
  php-apache:
    image: php:7.4-apache
    # build:
    #   context: ./php-apache
    ports:
      - 3001:80
    volumes:
      - ./dist_local_docker:/var/www/html:z
    links:
      - 'mysql'

  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    volumes:
      - doenet_db:/var/lib/mysql
    environment:
      TZ: "America/Chicago"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"
      # MYSQL_USER: 'root'
      # MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'doenet_local'

volumes:
  doenet_db: