version: '3.7'

services:
  apache:
    build: './apache'
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./volumes/dist_local:/usr/local/apache2/htdocs
    depends_on:
      - php
      - mysql
    restart: always

  php:
    build: './php'
    volumes:
      - ./volumes/dist_local:/usr/local/apache2/htdocs
      - ./php_config/env.ini:/var/doenet_php_config/env.ini
    restart: always

  mysql:
    build: './mysql'
    ports:
      - 3306:3306
    volumes:
      - ./volumes/db:/var/lib/mysql
    restart: always

  node:
    # build:
    #   context: '../'
    #   dockerfile: 'node'
    build: './node'
    # image: node:13.8
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ..:/home/node/app
      - ./volumes/dist_local:/var/www/html
    command: 'npm start' # comment this line if you want to serve but not build
    restart: always # comment this line if you want to serve but not build
    # command: 'npm --version' # Uncomment this line if you want to serve but not build
