version: '3.7'

services:
  apache:
    image: lyanthropos/donet_test:apache
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ../dist_local:/usr/local/apache2/htdocs
    depends_on:
      - php
      - mysql
    restart: always

  php:
    image: lyanthropos/donet_test:php
    volumes:
      - ../dist_local:/usr/local/apache2/htdocs
    restart: always

  mysql:
    image: lyanthropos/donet_test:mysql
    ports:
      - 3306:3306
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/db_init:/docker-entrypoint-initdb.d
    restart: always

  # node:
  #   build: './node'
  #   # image: node:13.8
