version: '3.7'

services:
  apache:
    build: '../doenet_docker/apache'
    ports:
      - 8080:80
      # - 443:443
    volumes:
      - ../dist_local:/usr/local/apache2/htdocs
    depends_on:
      - php
      - mysql
    restart: always

  php:
    build: '../doenet_docker/php'
    volumes:
      - ../dist_local:/usr/local/apache2/htdocs
    restart: always

  mysql:
    build: '../doenet_docker/mysql'
    ports:
      - 3306:3306
    volumes:
      - ../doenet_docker/volumes/db:/var/lib/mysql
      - ../doenet_docker/volumes/db_init:/docker-entrypoint-initdb.d
    restart: always
