name: Lint and CI

# To Do
# 2. Try out Cypress Dashboard
# 3. Look into differential testing
# 4. Caching Containers? 
# 5. Status Checks

# Runs on ubuntu because macOS is not licensed to have docker-compose

on:
  push:
    branches: [ master, Implement-CI ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    # Can crash if the number of modified files is extremely large
    # In most cases this is due to the user not merging in upstream/master before committing

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
        node-version: '10.x'
    - run: npm install -g eslint && npm install eslint-plugin-react
    - name: Linting src
      run: eslint $(git diff --name-only upstream/master -- ${GITHUB_REF##*/} | grep -E -- '^src' | xargs ls -d 2>/dev/null)
    - name: Linting cypress
      run: eslint $(git diff --name-only upstream/master -- ${GITHUB_REF##*/} | grep -E -- '^cypress' | xargs ls -d 2>/dev/null)

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install -g wait-on cypress && npm install
    # - name: Make dist_local Folder
    #   run: mkdir -m 777 dist_local 
    - name: Build the Containers
      run: npm run docker:build
    - name: Start the Server
      run: npm run deploy & wait-on http://localhost:3000
    - name: Run tagSpecific Tests
      run: cypress run -b 'chrome' --config video=false --spec "cypress/integration/tagSpecific/**"
