name: Lint and CI

# To Do
# 2. Try out Cypress Dashboard
# 3. Look into differential testing
# 4. Caching Containers? 
# 5. Status Checks

# Something else would be automated docs updating


on:
  push:
    branches: [ master, Implement-CI ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm install -g eslint
    - name: Linting
      run: eslint $(git diff --name-only --cached master | grep -E -- '^src|^cypress' | xargs ls -d 2>/dev/null)

  lint-and-test:

    runs-on: ubuntu-latest
    # macOS is not licensed to have docker-compose

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install && npm install -g wait-on
    # - name: Make dist_local Folder
    #   run: mkdir -m 777 dist_local 
    - name: Build the Containers
      run: npm run docker:build
    - name: Start the Server
      run: npm run deploy & wait-on http://localhost:3000
    - name: Run Tests
      run: npm run test:all
