name: Lint and CI

# Runs on ubuntu because macOS is not licensed to have docker-compose

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    # Only lints the file differences between the current branch and upstream/master
    runs-on: ubuntu-latest

    # Might crash if the number of modified files is extremely large
    # This is most likely due to the user not merging in upstream/master before committing

    # If the linter throws up a failure, run the linting command locally and ctr+f for 
    # "prettier-eslint [ERROR]" to figure out which file failed 

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
        node-version: '10.x'
    - run: npm install -g eslint && npm install eslint-plugin-react
    - name: Fetch upstream/master
      run: git remote add upstream https://github.com/Doenet/DoenetTools.git && git fetch upstream
    - name: What src files are being linted?
      run: git diff --name-only upstream/master | grep -E -- '^src' | xargs ls -d 2>/dev/null
    - name: Linting src
      run: eslint $(git diff --name-only upstream/master | grep -E -- '^src' | xargs ls -d 2>/dev/null)
    - name: Linting cypress
      run: eslint $(git diff --name-only upstream/master | grep -E -- '^cypress' | xargs ls -d 2>/dev/null)

# "lint": "prettier-eslint \"$(pwd)/src/**/*.js\" && prettier-eslint \"$(pwd)/cypress/**/*.js\"",

  test:
    # Only runs the tests found in 'cypress/integration/tagSpecific'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install -g wait-on cypress && npm install
    - name: Build the Containers
      run: npm run docker:build
    - name: Touch src/defaultCode.doenet
      # The mere existence of this file is required for cypress tests to pass
      run: touch src/defaultCode.doenet
    - name: Start the Server
      run: npm run deploy & wait-on http://localhost:3001
    - name: Run tagSpecific Tests
      run: cypress run -b 'chrome' --config video=false,screenshotOnRunFailure=false --spec "cypress/integration/tagSpecific/**"


      module.exports = {
        "env": {
          "browser": true,
          "es2020": true,
          "node": true
        },
        "extends": [
          "eslint:recommended",
          "plugin:react/recommended",
          "prettier"
        ],
        "parserOptions": {
          "ecmaFeatures": {
            "jsx": true
          },
          "ecmaVersion": 11,
          "sourceType": "module"
        },
        "plugins": [
          "react",
          "prettier"
        ],
        "rules": {
          "linebreak-style": [
            "error",
            "unix",
          ],
        },
        "settings": {
          "react": {
            "version": "detect"
          }
        }
      };
      